### ISSUE TITLE
[Q] Need an example to show how to generate an image.

### ISSUE THREAD

**Issue by showmin** [EugenHotaj/pytorch-generative#35] opened 2023-03-02 08:37 UTC
Hi Eugen,

I've followed the readme and successfully train imageGPT model by `reproduce`, but I have no idea how to generate an image with the trained model. I tend to train the model by 1, 2, 3, ... epochs and generate images for each stage to see what happens.

I checked the following code, but also have no idea what `sample_fn` should I assigned (it is `None` by default). Would you please add a simple example in the readme?

https://github.com/EugenHotaj/pytorch-generative/blob/36cf1eb32179163afe253ff3a95b500127253d83/pytorch_generative/trainer.py#L281-L285

**Comment by EugenHotaj** [comment] 2023-03-02 13:02
@showmin An example of how to pass the `sample_fn` is [here](https://github.com/EugenHotaj/pytorch-generative/blob/master/pytorch_generative/models/vae/vd_vae.py#L480-L484).

The `sample_fn` should call `model.sample()` and do any pre/post processing to convert the model samples into images. In the example above, we first call `model.sample()` to generate the raw samples then binarize the output to `0` or `1` since we're generating binarized MNIST images.

**Comment by EugenHotaj** [comment] 2023-03-02 14:04
@showmin I thought a bit more about the `sample_fn` and decided to remove it altogether because it's confusing. You should now no longer need to pass in `sample_fn` and can just set `sample_epochs` on the `Trainer`. The trainer will directly call `model.sample()`. Hopefully this is a lot easier :) .

**Comment by showmin** [comment] 2023-03-03 03:04
@EugenHotaj Thanks for the reply. That's really easier for me. Well, now I have to wait for the result after trainning 1 epoch but cannot restore the epoch that I've trained then generate the samples. It would be perfect for me if I can generate samples from trained epoch.

**Comment by EugenHotaj** [comment] 2023-03-03 03:12
@showmin If you want to generate samples at a particular epoch, the easiest thing to do is manually call `model.sample()` after you've loaded the checkpoint. The samples generated in the `Trainer` are mostly meant to track the progress during training.

**Comment by showmin** [comment] 2023-03-03 04:02
I try to add `self.sample_one_batch()` after the code:
https://github.com/EugenHotaj/pytorch-generative/blob/f9de41c6e01a39132d90d342ead28a4d7b4c7516/pytorch_generative/trainer.py#L230-L232

such that I can generate samples after I restore the latest epoch. But it came out an error:
```
Found 2 saved checkpoints.
Restoring trainer state from checkpoint trainer_state_2.ckpt.
Falied to sample from the model: 'ImageGPT' object has no attribute '_c'
```

**Comment by EugenHotaj** [comment] 2023-03-03 13:36
The issue is that we weren't saving some variables during checkpointing. I just landed 406a7becc2cff00a8f6a3459437b0bbc07bf6471 which should fix this issue _for new checkpoints only_.

**Comment by showmin** [comment] 2023-03-06 01:24
Still has the same error message. Does it only work for the new trained epoch after I checkout the latest code?

**Comment by EugenHotaj** [comment] 2023-03-06 02:37
Yes, like I said above it only works for new checkpoints unfortunately. For old checkpoints you'd need to manually use `model.sample`.

**Comment by showmin** [comment] 2023-03-06 04:56
After train a new epoch, errors here:
```
Found 3 saved checkpoints.
Restoring trainer state from checkpoint trainer_state_3.ckpt.
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    main(args)
  File "train.py", line 44, in main
    MODEL_DICT[args.model].reproduce(args.epochs, args.batch_size, args.logdir)
  File "D:\Jupyter_Home\pytorch-generative\pytorch_generative\models\autoregressive\image_gpt.py", line 175, in reproduce
    model_trainer.interleaved_train_and_eval(n_epochs)
  File "D:\Jupyter_Home\pytorch-generative\pytorch_generative\trainer.py", line 232, in interleaved_train_and_eval
    self.restore_checkpoint()
  File "D:\Jupyter_Home\pytorch-generative\pytorch_generative\trainer.py", line 134, in restore_checkpoint
    self.model.load_state_dict(checkpoint["model"])
  File "C:\Users\w00665547\Anaconda3\envs\env_ml\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageGPT:
        Unexpected key(s) in state_dict: "_c", "_h", "_w".
```

**Comment by showmin** [comment] 2023-03-10 03:18
It seems that the error was caused by putting register_buffer() in **call** method in ```base.py```. I tried to put them in **init** method and it removed the error successfully. If it is the root cause, probably you need to assign an input image when creating the object.

**Comment by EugenHotaj** [comment] 2023-03-10 13:20
@showmin busy week so just had a chance to look at this. You're right, the issue is that we create some dynamic buffers during `forward` which won't be present on a newly initialized model and loading the checkpoint will fail. I just pushed in 449795f2a49c40e488d83872ec627fbad368a1ee which should fix the issue. You should be able to load in any existing checkpoints now. 

Let me know if you're still seeing issues.

**Comment by showmin** [comment] 2023-03-13 05:31
@EugenHotaj Thanks. It works without any other issue.

**Comment by EugenHotaj** [comment] 2023-03-13 12:27
Great! Going to close this issue out, please feel free to open again if needed.

**Closed by EugenHotaj** 2023-03-13 12:27 UTC
